### ISSUE TITLE
any way to fix this?

### ISSUE THREAD

**Issue by JokerDotlua** [xT-Development/xt-prison#12]
![image](https://github.com/user-attachments/assets/21671077-dd4b-4e04-904d-89c67606a2a3)

**Comment by xThrasherrr** [comment]
This is a user error. You've changed the name of your target.

It's attempting to call an ox_target export, but for some reason, you have your target resource renamed or something completely unrelated to this script.

This is not an issue with prison.

**Comment by JokerDotlua** [comment]
yea i changed it to qb to see if it would help but it still gave me the same error code nothing changed when i did the error code is still the same as it was with ox-target

**Comment by xThrasherrr** [comment]
Make sure ox_target is ensured before xt-prison, that export exists in ox_target

https://overextended.dev/ox_target/Functions/Client#addspherezone

**Comment by JokerDotlua** [comment]
thanks i got it going do you know why i cant receive the Canteen Meal when i get it
