### ISSUE TITLE
commands not working

### ISSUE THREAD

**Issue by KostaZx** [xT-Development/xt-prison#2]
Framework: qbx_core

/jail ![image](https://github.com/user-attachments/assets/e2e2315d-70ce-4435-b339-f09b7af60282)
/jailtime 
![image](https://github.com/user-attachments/assets/b44d3232-1abe-4c98-9678-fae95e2af194)

**Comment by xThrasherrr** [comment]
Resolved with commit: https://github.com/xT-Development/xt-prison/commit/bab565734440ce6c154f9d90806fcc4bf599270d
